#!/usr/bin/env python3
"""
AI Context Accelerator - Generates compressed system knowledge for rapid AI onboarding
Enhanced with automatic session logging and git integration
"""

import json
import os
import subprocess
from datetime import datetime
import glob

def get_git_info():
    """Get recent git commit information for context"""
    try:
        # Get last 5 commits
        result = subprocess.run(['git', 'log', '--oneline', '-5'], 
                              capture_output=True, text=True, cwd='../..')
        commits = result.stdout.strip().split('\n') if result.stdout else []
        
        # Get current branch
        branch_result = subprocess.run(['git', 'branch', '--show-current'], 
                                     capture_output=True, text=True, cwd='../..')
        current_branch = branch_result.stdout.strip() if branch_result.stdout else 'main'
        
        # Get uncommitted changes
        status_result = subprocess.run(['git', 'status', '--porcelain'], 
                                     capture_output=True, text=True, cwd='../..')
        uncommitted_changes = len(status_result.stdout.strip().split('\n')) if status_result.stdout.strip() else 0
        
        return {
            "recent_commits": commits,
            "current_branch": current_branch,
            "uncommitted_changes": uncommitted_changes,
            "last_updated": datetime.now().isoformat()
        }
    except:
        return {
            "recent_commits": [],
            "current_branch": "main",
            "uncommitted_changes": 0,
            "last_updated": datetime.now().isoformat()
        }

def scan_session_logs():
    """Scan for existing session logs to include in context"""
    session_logs = []
    log_files = glob.glob('SESSION_LOG_*.md')
    
    for log_file in sorted(log_files, reverse=True)[:3]:  # Last 3 sessions
        try:
            with open(log_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # Extract key info from session log
                lines = content.split('\n')
                session_info = {
                    "file": log_file,
                    "preview": ' '.join(lines[:5])  # First 5 lines as preview
                }
                session_logs.append(session_info)
        except:
            continue
    
    return session_logs

def auto_create_session_log():
    """Automatically create/update today's session log"""
    today = datetime.now().strftime('%Y-%m-%d')
    session_file = f'SESSION_LOG_{today}.md'
    
    # Check if session log exists for today
    if not os.path.exists(session_file):
        git_info = get_git_info()
        
        with open(session_file, 'w', encoding='utf-8') as f:
            f.write(f"# Session Log: {today} - Development Session\n\n")
            f.write("## 📅 Session Overview\n")
            f.write(f"**Date**: {today}\n")
            f.write(f"**Auto-generated**: {datetime.now().strftime('%H:%M:%S')}\n")
            f.write(f"**Branch**: {git_info['current_branch']}\n\n")
            
            f.write("## 🔄 Recent Activity\n")
            f.write("**Recent Commits**:\n")
            for commit in git_info['recent_commits'][:3]:
                f.write(f"- {commit}\n")
            
            if git_info['uncommitted_changes'] > 0:
                f.write(f"\n**Uncommitted Changes**: {git_info['uncommitted_changes']} files\n")
            
            f.write("\n## 💡 Session Notes\n")
            f.write("*Add session-specific notes here as development progresses*\n\n")
            f.write("## 🎯 Key Changes Made\n")
            f.write("*Document major changes and decisions made during this session*\n\n")
            f.write("*Auto-generated by AI Context Accelerator*\n")
        
        print(f"📝 Created new session log: {session_file}")
    
    return session_file

def generate_ai_context_package():
    """Generate a comprehensive but concise AI context package"""
    
    # Get current git and session info
    git_info = get_git_info()
    session_logs = scan_session_logs()
    
    context = {
        "system_identity": {
            "name": "Finance Automation V10.1",
            "type": "Google Apps Script",
            "purpose": "Bank email → categorized spreadsheet automation",
            "scale": "273 functions, 11.8k lines",
            "success_metrics": "86.4% auto-categorization, 97 ML patterns"
        },
        
        "git_context": git_info,
        
        "recent_sessions": session_logs,
        
        "critical_knowledge": {
            "architecture_flow": "Gmail → _extractEmailDomain() → Bank parsers → ML categorization → Spreadsheet",
            "data_ecosystem": {
                "Failed_Parsing": "68 entries - parsing failure analysis",
                "AI_Learning": "97 patterns - ML categorization training",
                "Transactions": "22 items - processed financial data"
            },
            "recent_major_fixes": [
                "Domain extraction null pointer → try-catch validation",
                "CIBC purchase/credit confusion → priority logic reversal",
                "Menu redundancy (3 consolidation functions → 2 streamlined)"
            ]
        },
        
        "ai_assistant_priorities": [
            "Email parsing accuracy drives everything",
            "Domain extraction is critical failure point",
            "Bank-specific parsing logic varies significantly",
            "Menu UX follows help-first philosophy",
            "ML learning patterns feed categorization success"
        ],
        
        "common_issues": {
            "parsing_failures": "Check _extractEmailDomain() and bank-specific parsers",
            "categorization_errors": "Review AI_Learning patterns and ML logic",
            "menu_confusion": "Streamlined consolidation functions, Function Reference first",
            "performance_bottlenecks": "Currently 0 - system optimized"
        },
        
        "context_acceleration_tips": [
            "Start with Failed_Parsing sheet to understand current issues",
            "Review comprehensive_system_analysis.json for data relationships",
            "Check Function Reference system for user-facing documentation",
            "Email processing = 24 functions handling 5+ bank formats",
            "Menu system has 6 tiers: Reference → Main → Dashboard → Transactions → Maintenance → Import → Advanced",
            "Always use Chrome for HTML reports (user preference over VS Code Simple Browser)",
            "Check SESSION_LOG files for detailed development history and context"
        ],
        
        "recent_session_context": {
            "date": "2025-08-22",
            "focus": "Menu redundancy cleanup and AI context acceleration system",
            "changes": [
                "Removed 3 redundant consolidation menu items",
                "Moved Function Reference to first menu position",
                "Created comprehensive AI context acceleration system",
                "Organized context files into AI-Context-System subfolder"
            ],
            "user_preferences": [
                "Chrome browser over VS Code Simple Browser",
                "Detail-oriented UI feedback",
                "Values systematic analysis before changes",
                "Prefers comprehensive documentation and automation"
            ]
        },
        
        "last_updated": datetime.now().isoformat(),
        "evolution_stage": "Post-menu cleanup, Function Reference optimization"
    }
    
    return context

def save_context_package():
    """Save the AI context package for future use"""
    context = generate_ai_context_package()
    
    # Save as JSON for programmatic use
    with open('ai_context_package.json', 'w') as f:
        json.dump(context, f, indent=2)
    
    # Save as readable markdown
    with open('AI_ONBOARDING_GUIDE.md', 'w', encoding='utf-8') as f:
        f.write("# AI Assistant Onboarding Guide\n\n")
        f.write("*Rapid context acceleration for Finance Automation system*\n\n")
        
        f.write("## 🎯 System Identity\n")
        for key, value in context["system_identity"].items():
            f.write(f"- **{key.replace('_', ' ').title()}**: {value}\n")
        
        f.write("\n## 🧠 Critical Knowledge\n")
        f.write(f"**Architecture**: {context['critical_knowledge']['architecture_flow']}\n\n")
        
        f.write("**Data Ecosystem**:\n")
        for sheet, desc in context["critical_knowledge"]["data_ecosystem"].items():
            f.write(f"- {sheet}: {desc}\n")
        
        f.write("\n**Recent Major Fixes**:\n")
        for fix in context["critical_knowledge"]["recent_major_fixes"]:
            f.write(f"- {fix}\n")
        
        f.write("\n## 🚀 AI Assistant Priorities\n")
        for priority in context["ai_assistant_priorities"]:
            f.write(f"- {priority}\n")
        
        f.write("\n## 🔧 Common Issues & Solutions\n")
        for issue, solution in context["common_issues"].items():
            f.write(f"- **{issue.replace('_', ' ').title()}**: {solution}\n")
        
        f.write("\n## ⚡ Context Acceleration Tips\n")
        for tip in context["context_acceleration_tips"]:
            f.write(f"- {tip}\n")
        
        f.write(f"\n*Generated: {context['last_updated']}*\n")
    
    print("✅ AI context package generated:")
    print("  📄 ai_context_package.json (programmatic)")
    print("  📖 AI_ONBOARDING_GUIDE.md (human-readable)")

if __name__ == "__main__":
    session_file = save_context_package()
    print(f"\\n📋 Session Management:")
    print(f"   📝 Auto-created/updated: {session_file}")
    print(f"   🔄 Run this script after each development session")
    print(f"   📚 Session logs preserve development context for future AI sessions")
